import { DEFAULT_USERS } from "./models.js";

const now = new Date("2026-05-23T12:00:00+02:00");

const daysAgo = (days) => {
  const date = new Date(now);
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

const daysFromNow = (days) => {
  const date = new Date(now);
  date.setDate(date.getDate() + days);
  return date.toISOString();
};

export const demoData = {
  users: DEFAULT_USERS,
  currentUserId: "u-1",
  leads: [
    {
      id: "lead-1",
      companyName: "Hidra Talleres SL",
      contactName: "Nerea Campos",
      email: "nerea@hidratalleres.es",
      phone: "+34 611 204 882",
      sector: "Industrial",
      employees: 42,
      city: "Valencia",
      source: "LinkedIn",
      status: "Nuevo",
      priority: "Alta",
      createdAt: daysAgo(2),
      lastInteractionAt: daysAgo(2),
      nextActionAt: daysFromNow(1),
      nextAction: "Primera llamada consultiva",
      notes: "Quiere revisar contratos laborales y compliance basico.",
      ownerId: "u-2",
      recommendedPlan: "Pro",
      estimatedMonthlyRevenue: 590,
      riskScore: 78,
    },
    {
      id: "lead-2",
      companyName: "NovaClinic Dental",
      contactName: "Jorge Prieto",
      email: "jorge@novaclinic.es",
      phone: "+34 699 881 202",
      sector: "Sanidad",
      employees: 18,
      city: "Madrid",
      source: "Web",
      status: "Contactado",
      priority: "Media",
      createdAt: daysAgo(6),
      lastInteractionAt: daysAgo(4),
      nextActionAt: daysFromNow(2),
      nextAction: "Enviar casos de uso para clinicas",
      notes: "Interesado en proteccion de datos y consentimientos.",
      ownerId: "u-2",
      recommendedPlan: "Starter",
      estimatedMonthlyRevenue: 290,
      riskScore: 63,
    },
    {
      id: "lead-3",
      companyName: "Cumbre Logistics",
      contactName: "Daniel Rios",
      email: "daniel@cumbrelogistics.com",
      phone: "+34 622 017 438",
      sector: "Logistica",
      employees: 96,
      city: "Zaragoza",
      source: "Referido",
      status: "Demo agendada",
      priority: "Alta",
      createdAt: daysAgo(5),
      lastInteractionAt: daysAgo(1),
      nextActionAt: daysFromNow(3),
      nextAction: "Demo de diagnostico empresarial",
      notes: "Viene recomendado por asesor externo. Potencial Premium.",
      ownerId: "u-2",
      recommendedPlan: "Premium",
      estimatedMonthlyRevenue: 990,
      riskScore: 84,
    },
    {
      id: "lead-4",
      companyName: "Aurora E-commerce",
      contactName: "Lucia Merino",
      email: "lucia@aurorastore.es",
      phone: "+34 633 310 554",
      sector: "E-commerce",
      employees: 12,
      city: "Barcelona",
      source: "Campana",
      status: "Demo realizada",
      priority: "Alta",
      createdAt: daysAgo(12),
      lastInteractionAt: daysAgo(8),
      nextActionAt: daysAgo(1),
      nextAction: "Enviar propuesta Pro",
      notes: "La demo fue positiva, falta propuesta formal.",
      ownerId: "u-2",
      recommendedPlan: "Pro",
      estimatedMonthlyRevenue: 590,
      riskScore: 71,
    },
    {
      id: "lead-5",
      companyName: "Boreal Arquitectura",
      contactName: "Sergio Lamas",
      email: "sergio@borealarq.es",
      phone: "+34 644 392 127",
      sector: "Servicios profesionales",
      employees: 9,
      city: "Bilbao",
      source: "WhatsApp",
      status: "Propuesta enviada",
      priority: "Media",
      createdAt: daysAgo(10),
      lastInteractionAt: daysAgo(3),
      nextActionAt: daysFromNow(1),
      nextAction: "Seguimiento de propuesta",
      notes: "Evalua Starter vs Pro.",
      ownerId: "u-2",
      recommendedPlan: "Starter",
      estimatedMonthlyRevenue: 290,
      riskScore: 55,
    },
    {
      id: "lead-6",
      companyName: "Materia Food Lab",
      contactName: "Paula Benitez",
      email: "paula@materiafoodlab.es",
      phone: "+34 655 458 901",
      sector: "Alimentacion",
      employees: 33,
      city: "Sevilla",
      source: "Evento",
      status: "Negociacion",
      priority: "Alta",
      createdAt: daysAgo(19),
      lastInteractionAt: daysAgo(2),
      nextActionAt: daysFromNow(4),
      nextAction: "Revisar descuento anual",
      notes: "Quiere incluir revision de proveedores y etiquetado.",
      ownerId: "u-1",
      recommendedPlan: "Premium",
      estimatedMonthlyRevenue: 890,
      riskScore: 82,
    },
    {
      id: "lead-7",
      companyName: "Senda Tech",
      contactName: "Mikel Arana",
      email: "mikel@sendatech.io",
      phone: "+34 666 120 440",
      sector: "Software",
      employees: 27,
      city: "San Sebastian",
      source: "LinkedIn",
      status: "Interesado",
      priority: "Media",
      createdAt: daysAgo(4),
      lastInteractionAt: daysAgo(1),
      nextActionAt: daysFromNow(2),
      nextAction: "Compartir plantilla DPA",
      notes: "Busca generar contratos SaaS y politicas internas.",
      ownerId: "u-2",
      recommendedPlan: "Pro",
      estimatedMonthlyRevenue: 590,
      riskScore: 68,
    },
    {
      id: "lead-8",
      companyName: "Kilometro Cero Retail",
      contactName: "Ana Blasco",
      email: "ana@km0retail.es",
      phone: "+34 677 442 099",
      sector: "Retail",
      employees: 58,
      city: "Alicante",
      source: "Web",
      status: "Contactado",
      priority: "Baja",
      createdAt: daysAgo(15),
      lastInteractionAt: daysAgo(10),
      nextActionAt: daysAgo(2),
      nextAction: "Reactivar contacto",
      notes: "Sin respuesta desde el primer email.",
      ownerId: "u-2",
      recommendedPlan: "Starter",
      estimatedMonthlyRevenue: 290,
      riskScore: 48,
    },
    {
      id: "lead-9",
      companyName: "Argos Instalaciones",
      contactName: "Ramon Cid",
      email: "ramon@argosinstalaciones.es",
      phone: "+34 688 702 522",
      sector: "Construccion",
      employees: 74,
      city: "Murcia",
      source: "Referido",
      status: "Cliente ganado",
      priority: "Alta",
      createdAt: daysAgo(28),
      lastInteractionAt: daysAgo(3),
      nextActionAt: daysFromNow(8),
      nextAction: "Onboarding legal",
      notes: "Convertido en cliente beta.",
      ownerId: "u-1",
      recommendedPlan: "Premium",
      estimatedMonthlyRevenue: 990,
      riskScore: 88,
      convertedClientId: "client-1",
    },
    {
      id: "lead-10",
      companyName: "Liria Academy",
      contactName: "Carmen Ortego",
      email: "carmen@liriaacademy.es",
      phone: "+34 690 120 334",
      sector: "Educacion",
      employees: 21,
      city: "Granada",
      source: "Otro",
      status: "Perdido",
      priority: "Baja",
      createdAt: daysAgo(22),
      lastInteractionAt: daysAgo(5),
      nextActionAt: "",
      nextAction: "Sin accion",
      notes: "No tiene presupuesto este trimestre.",
      ownerId: "u-2",
      recommendedPlan: "Starter",
      estimatedMonthlyRevenue: 0,
      riskScore: 34,
    },
  ],
  clients: [
    {
      id: "client-1",
      leadId: "lead-9",
      businessName: "Argos Instalaciones SL",
      taxId: "B88412031",
      address: "Calle Industria 18, Murcia",
      primaryContact: "Ramon Cid",
      billingEmail: "facturacion@argosinstalaciones.es",
      plan: "Premium",
      monthlyPrice: 990,
      signupDate: daysAgo(3),
      renewalDate: daysFromNow(362),
      status: "Activo",
      legalReviewPending: true,
      ownerId: "u-3",
    },
    {
      id: "client-2",
      businessName: "Marisma Hotels SL",
      taxId: "B92773481",
      address: "Avenida del Puerto 44, Malaga",
      primaryContact: "Elena Pardo",
      billingEmail: "admin@marismahotels.es",
      plan: "Pro",
      monthlyPrice: 590,
      signupDate: daysAgo(46),
      renewalDate: daysFromNow(319),
      status: "Pendiente de pago",
      legalReviewPending: false,
      ownerId: "u-3",
    },
    {
      id: "client-3",
      businessName: "Delta Asesores SCP",
      taxId: "J01888421",
      address: "Paseo Central 9, Madrid",
      primaryContact: "Victor Coll",
      billingEmail: "victor@deltaasesores.es",
      plan: "Starter",
      monthlyPrice: 290,
      signupDate: daysAgo(31),
      renewalDate: daysFromNow(334),
      status: "Activo",
      legalReviewPending: false,
      ownerId: "u-4",
    },
    {
      id: "client-4",
      businessName: "Iberica Biofarma SL",
      taxId: "B53668121",
      address: "Parque Tecnologico 6, Valencia",
      primaryContact: "Aitana Mas",
      billingEmail: "finance@ibericabiofarma.es",
      plan: "Personalizado",
      monthlyPrice: 1450,
      signupDate: daysAgo(67),
      renewalDate: daysFromNow(298),
      status: "En revision",
      legalReviewPending: true,
      ownerId: "u-3",
    },
    {
      id: "client-5",
      businessName: "Trama Creativa SL",
      taxId: "B67229104",
      address: "Calle Norte 77, Barcelona",
      primaryContact: "Mario Gil",
      billingEmail: "mario@tramacreativa.es",
      plan: "Pro",
      monthlyPrice: 590,
      signupDate: daysAgo(90),
      renewalDate: daysFromNow(275),
      status: "Cancelado",
      legalReviewPending: false,
      ownerId: "u-1",
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Llamar a Hidra Talleres",
      description: "Validar necesidad principal y confirmar decisor.",
      relatedType: "lead",
      relatedId: "lead-1",
      dueDate: daysFromNow(1),
      priority: "Alta",
      status: "Pendiente",
      ownerId: "u-2",
    },
    {
      id: "task-2",
      title: "Enviar propuesta a Aurora",
      description: "Preparar propuesta Pro con clausulas e-commerce.",
      relatedType: "lead",
      relatedId: "lead-4",
      dueDate: daysAgo(1),
      priority: "Alta",
      status: "Pendiente",
      ownerId: "u-2",
    },
    {
      id: "task-3",
      title: "Revisar pago Marisma",
      description: "Contactar por factura pendiente.",
      relatedType: "client",
      relatedId: "client-2",
      dueDate: daysAgo(2),
      priority: "Media",
      status: "Pendiente",
      ownerId: "u-4",
    },
    {
      id: "task-4",
      title: "Demo Cumbre Logistics",
      description: "Mostrar diagnostico, documentos e indicadores de riesgo.",
      relatedType: "lead",
      relatedId: "lead-3",
      dueDate: daysFromNow(3),
      priority: "Alta",
      status: "En curso",
      ownerId: "u-2",
    },
    {
      id: "task-5",
      title: "Revision legal Argos",
      description: "Primera revision de contratos de subcontratas.",
      relatedType: "client",
      relatedId: "client-1",
      dueDate: daysFromNow(4),
      priority: "Alta",
      status: "Pendiente",
      ownerId: "u-3",
    },
    {
      id: "task-6",
      title: "Enviar DPA a Senda Tech",
      description: "Compartir ejemplo de documento y alcance Pro.",
      relatedType: "lead",
      relatedId: "lead-7",
      dueDate: daysFromNow(2),
      priority: "Media",
      status: "Pendiente",
      ownerId: "u-2",
    },
    {
      id: "task-7",
      title: "Cerrar descuento Materia",
      description: "Validar descuento anual maximo con direccion.",
      relatedType: "lead",
      relatedId: "lead-6",
      dueDate: daysFromNow(4),
      priority: "Alta",
      status: "En curso",
      ownerId: "u-1",
    },
    {
      id: "task-8",
      title: "Reactivar Kilometro Cero",
      description: "Enviar mensaje breve de seguimiento.",
      relatedType: "lead",
      relatedId: "lead-8",
      dueDate: daysAgo(2),
      priority: "Baja",
      status: "Pendiente",
      ownerId: "u-2",
    },
    {
      id: "task-9",
      title: "Actualizar diagnostico Iberica",
      description: "Revisar evidencias pendientes de compliance sanitario.",
      relatedType: "client",
      relatedId: "client-4",
      dueDate: daysFromNow(5),
      priority: "Alta",
      status: "Pendiente",
      ownerId: "u-3",
    },
    {
      id: "task-10",
      title: "Registrar llamada Delta",
      description: "Anotar feedback de onboarding.",
      relatedType: "client",
      relatedId: "client-3",
      dueDate: daysFromNow(1),
      priority: "Media",
      status: "Completada",
      ownerId: "u-4",
    },
  ],
  interactions: [
    {
      id: "int-1",
      type: "Llamada",
      relatedType: "lead",
      relatedId: "lead-1",
      date: daysAgo(2),
      description: "Primer contacto por LinkedIn. Solicita llamada esta semana.",
      createdBy: "u-2",
    },
    {
      id: "int-2",
      type: "Email",
      relatedType: "lead",
      relatedId: "lead-2",
      date: daysAgo(4),
      description: "Enviado resumen de riesgos habituales en clinicas dentales.",
      createdBy: "u-2",
    },
    {
      id: "int-3",
      type: "Demo",
      relatedType: "lead",
      relatedId: "lead-4",
      date: daysAgo(8),
      description: "Demo completada con buena recepcion. Falta propuesta.",
      createdBy: "u-2",
    },
    {
      id: "int-4",
      type: "WhatsApp",
      relatedType: "lead",
      relatedId: "lead-5",
      date: daysAgo(3),
      description: "Confirma que revisara la propuesta el lunes.",
      createdBy: "u-2",
    },
    {
      id: "int-5",
      type: "Reunion",
      relatedType: "lead",
      relatedId: "lead-6",
      date: daysAgo(2),
      description: "Negociacion de paquete Premium anual.",
      createdBy: "u-1",
    },
    {
      id: "int-6",
      type: "Cambio de estado",
      relatedType: "lead",
      relatedId: "lead-9",
      date: daysAgo(3),
      description: "Lead convertido en cliente Premium.",
      createdBy: "u-1",
    },
    {
      id: "int-7",
      type: "Nota manual",
      relatedType: "client",
      relatedId: "client-1",
      date: daysAgo(1),
      description: "Pendiente documentacion de subcontratacion.",
      createdBy: "u-3",
    },
    {
      id: "int-8",
      type: "Email",
      relatedType: "client",
      relatedId: "client-2",
      date: daysAgo(6),
      description: "Recordatorio de factura enviado.",
      createdBy: "u-4",
    },
    {
      id: "int-9",
      type: "Llamada",
      relatedType: "client",
      relatedId: "client-4",
      date: daysAgo(3),
      description: "Solicitan revision adicional sobre proveedores criticos.",
      createdBy: "u-3",
    },
    {
      id: "int-10",
      type: "Propuesta enviada",
      relatedType: "lead",
      relatedId: "lead-5",
      date: daysAgo(4),
      description: "Propuesta Starter enviada con opcion Pro.",
      createdBy: "u-2",
    },
  ],
  proposals: [
    {
      id: "prop-1",
      relatedLeadId: "lead-5",
      relatedClientId: "",
      plan: "Starter",
      price: 290,
      discount: 0,
      status: "Enviada",
      sentAt: daysAgo(4),
      expiresAt: daysFromNow(10),
      notes: "Incluye diagnostico inicial y 3 documentos.",
      ownerId: "u-2",
    },
    {
      id: "prop-2",
      relatedLeadId: "lead-6",
      relatedClientId: "",
      plan: "Premium",
      price: 990,
      discount: 10,
      status: "Enviada",
      sentAt: daysAgo(2),
      expiresAt: daysFromNow(12),
      notes: "Descuento anual condicionado a pago trimestral.",
      ownerId: "u-1",
    },
    {
      id: "prop-3",
      relatedLeadId: "lead-9",
      relatedClientId: "client-1",
      plan: "Premium",
      price: 990,
      discount: 0,
      status: "Aceptada",
      sentAt: daysAgo(6),
      expiresAt: daysFromNow(24),
      notes: "Aceptada para beta privada.",
      ownerId: "u-1",
    },
    {
      id: "prop-4",
      relatedLeadId: "lead-10",
      relatedClientId: "",
      plan: "Starter",
      price: 290,
      discount: 15,
      status: "Rechazada",
      sentAt: daysAgo(14),
      expiresAt: daysAgo(2),
      notes: "No encaja por presupuesto.",
      ownerId: "u-2",
    },
    {
      id: "prop-5",
      relatedLeadId: "lead-4",
      relatedClientId: "",
      plan: "Pro",
      price: 590,
      discount: 0,
      status: "Borrador",
      sentAt: "",
      expiresAt: daysFromNow(14),
      notes: "Pendiente adaptar alcance e-commerce.",
      ownerId: "u-2",
    },
  ],
  payments: [
    { id: "pay-1", clientId: "client-1", amount: 990, dueDate: daysFromNow(27), paidAt: daysAgo(2), status: "paid" },
    { id: "pay-2", clientId: "client-2", amount: 590, dueDate: daysAgo(5), paidAt: "", status: "pending" },
    { id: "pay-3", clientId: "client-3", amount: 290, dueDate: daysFromNow(9), paidAt: daysAgo(20), status: "paid" },
    { id: "pay-4", clientId: "client-4", amount: 1450, dueDate: daysFromNow(3), paidAt: "", status: "pending" },
    { id: "pay-5", clientId: "client-5", amount: 590, dueDate: daysAgo(14), paidAt: "", status: "failed" },
  ],
  documents: [
    { id: "doc-1", relatedType: "client", relatedId: "client-1", name: "Contrato Premium Argos", type: "contract", createdAt: daysAgo(3) },
    { id: "doc-2", relatedType: "client", relatedId: "client-4", name: "Informe compliance sanitario", type: "diagnostic", createdAt: daysAgo(12) },
    { id: "doc-3", relatedType: "lead", relatedId: "lead-5", name: "Propuesta Boreal", type: "proposal", createdAt: daysAgo(4) },
    { id: "doc-4", relatedType: "client", relatedId: "client-2", name: "Pack contratos hoteleros", type: "other", createdAt: daysAgo(18) },
  ],
  notes: [
    { id: "note-1", relatedType: "lead", relatedId: "lead-6", body: "Buen encaje para plan Premium si se incluye revision de proveedores.", createdAt: daysAgo(2), createdBy: "u-1" },
    { id: "note-2", relatedType: "client", relatedId: "client-1", body: "Cliente beta prioritario. Cuidar onboarding.", createdAt: daysAgo(1), createdBy: "u-3" },
  ],
  activityLog: [
    {
      id: "log-1",
      entityType: "lead",
      entityId: "lead-9",
      action: "convert",
      detail: "Lead convertido en cliente Premium.",
      createdAt: daysAgo(3),
      createdBy: "u-1",
    },
  ],
};
